[phases.install]
cmds = ["bundle install --deployment --jobs 4 --retry 3"]

[phases.build]
cmds = ["LANG=en_US.UTF-8 JEKYLL_ENV=production bundle exec jekyll build"]

[start]
cmd = "bundle exec ruby server.rb"

