[phases.install]
cmds = ["bundle install --deployment --jobs 4 --retry 3"]

[phases.build]
cmds = ["export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && JEKYLL_ENV=production bundle exec jekyll build"]

[start]
cmd = "ruby server.rb"

